# Generated by Django 5.0.1 on 2024-03-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='price',
            new_name='list_price',
        ),
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
