# Generated by Django 5.0.1 on 2024-03-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_price_listings_list_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='current_price',
        ),
        migrations.AddField(
            model_name='listings',
            name='highest_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
